---
- name: Download dotfiles
  git: >
    repo=git@github.com:markchalloner/dotfiles.git
    dest=~/dotfiles

- name: Link dotfiles directory
  file: >
    src=~/dotfiles
    dest=~/.link-files 
    state=link

- name: Install dotfiles
  command: link-files -i -o

