---
- hosts: all
  remote_user: vagrant
  vars:
    servername: www.ubuntu-trusty-vm.test ubuntu-trusty-vm.test 192.168.33.99
    timezone: Europe/London
  vars_files:
    - vars/common.yml
  roles:
    - init
